# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '__first__'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('fileseq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.FileSeq', verbose_name='\u0424\u0430\u0439\u043b\u044b')),
                ('docno', models.CharField(db_index=True, max_length=32, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('docdate', models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('docsum', models.DecimalField(db_index=True, decimal_places=2, max_digits=11, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contracts', to='bills.Approver', verbose_name='\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_contracts', to='bills.Department', verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_contracts', to='bills.Payer', verbose_name='\u041f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_contracts', to='bills.Place', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_contracts', to='core.Org', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_contracts', to='bills.State', verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_contracts', to='bills.Subject', verbose_name='\u041f\u043e\u0434\u041e\u0431\u044a\u0435\u043a\u0442')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0433\u043e\u0432\u043e\u0440',
                'verbose_name_plural': '\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u0430',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0414\u0430\u0442\u0430\u0412\u0440\u0435\u043c\u044f')),
                ('comment', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u041a\u0430\u043c\u043c\u0435\u043d\u0442\u044b')),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bills.Approver', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='\u0414\u043e\u0433\u043e\u0432\u043e\u0440')),
            ],
            options={
                'ordering': ('ctime',),
                'verbose_name': '\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0438\u044f',
                'verbose_name_plural': '\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(db_index=True, default=False, verbose_name='\u0421\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u043e')),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bills.Approver', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Contract', verbose_name='\u0414\u043e\u0433\u043e\u0432\u043e\u0440')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bills.Role', verbose_name='\u0420\u043e\u043b\u044c')),
            ],
            options={
                'ordering': ('contract',),
                'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442',
                'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('contract', 'role')]),
        ),
    ]
