# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='docdate',
            field=models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0433\u043e\u0432\u043e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='docno',
            field=models.CharField(db_index=True, max_length=32, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u0433\u043e\u0432\u043e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='docsum',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=11, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0434\u043e\u0433\u043e\u0432\u043e\u0440\u0430'),
        ),
    ]
