SET FOREIGN_KEY_CHECKS = 0;
BEGIN;
DROP TABLE IF EXISTS auth_group;
DROP TABLE IF EXISTS auth_group_permissions;
DROP TABLE IF EXISTS auth_permission;
DROP TABLE IF EXISTS auth_user;
DROP TABLE IF EXISTS auth_user_groups;
DROP TABLE IF EXISTS auth_user_user_permissions;
DROP TABLE IF EXISTS bills_approver;
DROP TABLE IF EXISTS bills_bill;
DROP TABLE IF EXISTS bills_department;
DROP TABLE IF EXISTS bills_event;
DROP TABLE IF EXISTS bills_payer;
DROP TABLE IF EXISTS bills_place;
DROP TABLE IF EXISTS bills_role;
DROP TABLE IF EXISTS bills_route;
DROP TABLE IF EXISTS bills_state;
DROP TABLE IF EXISTS bills_subject;
DROP TABLE IF EXISTS core_file;
DROP TABLE IF EXISTS core_fileseq;
DROP TABLE IF EXISTS core_fileseqitem;
DROP TABLE IF EXISTS core_org;
DROP TABLE IF EXISTS django_admin_log;
DROP TABLE IF EXISTS django_content_type;
DROP TABLE IF EXISTS django_session;
DROP TABLE IF EXISTS django_site;
DROP TABLE IF EXISTS scan_event;
DROP TABLE IF EXISTS scan_scan;
COMMIT;
