# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 16:38
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.my_upload_to, verbose_name='\u0424\u0430\u0439\u043b')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='\u0418\u043c\u044f \u0444\u0430\u0439\u043b\u0430')),
                ('mime', models.CharField(db_index=True, max_length=16, verbose_name='\u0422\u0438\u043f Mime')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0417\u0430\u043f\u0438\u0441\u0430\u043d\u043e')),
                ('size', models.PositiveIntegerField(db_index=True, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440')),
                ('md5', models.CharField(db_index=True, max_length=32, verbose_name='MD5')),
            ],
            options={
                'verbose_name': '\u0424\u0430\u0439\u043b',
                'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='FileSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '\u041f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0444\u0430\u0439\u043b\u043e\u0432',
                'verbose_name_plural': '\u041f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0444\u0430\u0439\u043b\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='\u0418\u041d\u041d')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('fullname', models.CharField(db_index=True, max_length=64, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='FileSeqItem',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.File', verbose_name='\u0424\u0430\u0439\u043b')),
                ('order', models.PositiveSmallIntegerField(db_index=True, verbose_name='#')),
                ('fileseq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FileSeq', verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0444\u0430\u0439\u043b\u043e\u0432')),
            ],
            options={
                'ordering': ('file', 'order'),
                'verbose_name': '\u0424\u0430\u0439\u043b \u043f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b \u043f\u043e\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.AddField(
            model_name='fileseq',
            name='files',
            field=models.ManyToManyField(through='core.FileSeqItem', to='core.File', verbose_name='\u0424\u0430\u0439\u043b\u044b'),
        ),
    ]
