# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-09 12:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.CharField(db_index=True, max_length=64, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442')),
                ('resume', models.BooleanField(db_index=True, verbose_name='\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0438\u044f')),
                ('ctime', models.DateTimeField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430\u0412\u0440\u0435\u043c\u044f')),
                ('comment', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='\u041a\u0430\u043c\u043c\u0435\u043d\u0442\u044b')),
            ],
            options={
                'ordering': ('ctime',),
                'verbose_name': '\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0438\u044f',
                'verbose_name_plural': '\u0420\u0435\u0437\u043e\u043b\u044e\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('fileseq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.FileSeq', verbose_name='\u0424\u0430\u0439\u043b\u044b')),
                ('place', models.CharField(db_index=True, max_length=24, verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='\u041f\u043e\u0434\u043e\u0431\u044a\u0435\u043a\u0442')),
                ('depart', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('payer', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0435\u043b\u044c\u0449\u0438\u043a')),
                ('supplier', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u041f\u0440\u043e\u0434\u0430\u0432\u0435\u0446')),
                ('no', models.CharField(db_index=True, max_length=32, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('date', models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('sum', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=11, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('events', models.TextField(blank=True, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0440\u0438\u044f')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Org', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a')),
            ],
            options={
                'ordering': ('fileseq',),
                'verbose_name': '\u0421\u043a\u0430\u043d',
                'verbose_name_plural': '\u0421\u043a\u0430\u043d\u044b',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.Scan', verbose_name='\u0421\u043a\u0430\u043d'),
        ),
    ]
