# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrarch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrarch',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
    ]
